# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [91]:
from scipy import stats 
import numpy as np
import pandas as pd

In [92]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [93]:
from scipy.stats import ttest_1samp, ttest_ind,levene, f_oneway, chisquare, chi2_contingency,zscore, ttest_rel, norm

In [94]:
t_statistic, p_value = ttest_1samp(GPU1,0)

p_value

7.228892044970457e-15

As the p_value is far less than 0.05. Reject the null hypoyhesis i.e.the mean value of the GPU1 is equal to zero.

## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [95]:
t_statistic, p_value = ttest_ind(GPU1,GPU2)

p_value

0.013794282041452725

Conclusion

p_value < 0.05

Reject Null Hypothesis i.e.There is enough evidence in favour of Alternative Hypothesis.

## Question 3

He is trying a third GPU - GPU3.

In [96]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

H0 : There is significant difference between speeds of GPU1, GPU2                                                             H1 : There is no significant difference between speeds of GPU1, GPU2

In [97]:
ttest_ind(GPU1,GPU3)

Ttest_indResult(statistic=-1.4988943759093303, pvalue=0.14509210993138993)

Conclusion
1. pvalue > 0.05
2. Do not reject null hypothesis.

## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [98]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

H0 : All Variances are equal

H1 : All Variances are not equal

In [99]:
levene(e1,e2,e3)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

Conclusion

pvalue > 0.05

Do not reject Null Hypothesis. We can depend on the result of ANOVA.

## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

H0: The three groups e1, e2, e3 have the same Population mean.
    
H1 : The three groups e1, e2, e3 have different population mean.

In [100]:
f,p = f_oneway(e1,e2,e3)

print('F value',f)
print('P value',p)

F value 2.51357622845924
P value 0.13574644501798466


Since pvalue > 0.05. Do not reject null hypothesis. We can say that the groups e1, e2, e3 have the same population mean.

## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

Type-I Error

    A Type-I Error occurs when the hypothesis testing concluded to reject the null hypothesis but actually it is not supposed to be rejected. In this scenario, we will take up some corrective measures for the process to which hypothesis testing is conducted even though not required.
    
Type-II Error

    A Type-II Error occurs when the hypothesis testing concluded do not reject the null hypothesis but actually it is supposed to be rejected. In this scenario, we will not take up any corrective measures for the process to which the hypothesis testing is conducted even though required.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


H0 : The waiting time to place an order has changed.(u not equal to 4.5)

H1 : The waiting time to place an order has not changed (u is equal to 4.5)

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [101]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [102]:
df = pd.DataFrame(dice,index=['d1','d2','d3','d4','d5','d6'],columns=['p1','p2','p3','p4'])
df

p1  p2  p3  p4
d1   5   8   3   8
d2   9   6   8   5
d3   8  12   7   2
d4   4  16   7   3
d5   3   9   6   5
d6   7   2   5   7

In [103]:
cont_table = pd.crosstab(index=df.index, columns=[df['p1'],df['p2'],df['p3'],df['p4']])

cont_table

p1     3  4  5  7  8  9
p2    9  16 8  2  12 6 
p3     6  7  3  5  7  8
p4     5  3  8  7  2  5
row_0                  
d1     0  0  1  0  0  0
d2     0  0  0  0  0  1
d3     0  0  0  0  1  0
d4     0  1  0  0  0  0
d5     1  0  0  0  0  0
d6     0  0  0  1  0  0

In [104]:
chi_statistic, p_value, dof, contingency = chi2_contingency(cont_table)

print('chi2 statistic ', chi_statistic)
print('---------------------------------')
print('pvalue ',p_value)
print('----------------------------------')
print('degrees of freedom', dof)
print('----------------------------------')
print('contingency ', contingency)

chi2 statistic  30.00000000000001
---------------------------------
pvalue  0.22428900483440337
----------------------------------
degrees of freedom 25
----------------------------------
contingency  [[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [105]:
z_score_values = zscore(dice)

z_score_values

array([[-0.46291005, -0.18884739, -1.83711731,  1.44115338],
       [ 1.38873015, -0.64208114,  1.22474487,  0.        ],
       [ 0.9258201 ,  0.7176201 ,  0.61237244, -1.44115338],
       [-0.9258201 ,  1.62408759,  0.61237244, -0.96076892],
       [-1.38873015,  0.03776948,  0.        ,  0.        ],
       [ 0.46291005, -1.54854863, -0.61237244,  0.96076892]])

In [106]:
p_values = norm.sf(abs(z_score_values)) * 2

print(p_values)

print(p_values.mean())

[[0.64342884 0.85021243 0.06619258 0.14954135]
 [0.16491482 0.5208205  0.22067136 1.        ]
 [0.35453948 0.47299156 0.54029137 0.14954135]
 [0.35453948 0.10435712 0.54029137 0.33666837]
 [0.16491482 0.96987148 1.         1.        ]
 [0.64342884 0.12149026 0.54029137 0.33666837]]
0.4685694646738299


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [107]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

H0 : The two groups have the same mean

H1 : The two groups does not have same mean.

In [108]:
t_statistic, p_value = ttest_rel(before,after)

print('t-staistic', before)

print('-----------------------')

print('p-value ', p_value)

t-staistic [103.86094929  33.5724115   83.00953462  89.39526115  64.12181983
 127.30242687 107.19245368 104.35345894 107.90208473  81.99227998
  78.4347825  144.25373639  86.20463027  57.67874131  96.58889521
 114.67110873 106.08649395 108.61035824 125.95525564  95.63828273
  82.29638585  96.50683424 105.46349977 134.57073633  79.10021592
  84.33619459  91.74168312  75.37112206 112.54331328 117.44062699
 133.52583982  70.05065697  86.67744615  97.92524184 130.91902966
 117.04797627 145.063642    91.26959319  45.32282102 108.76259876
  75.20715927 166.01649664 118.11739503 120.16016747 121.51869386
  59.75227998 145.43449506 103.06557393 119.30786825  77.05084789
 128.44350657  86.21216319 176.43048058 118.29006993  57.73520665
  93.03846238  90.33556661  64.54349005  46.24923901 121.74212111
  51.1568563   96.35477211  86.77470943 128.29762398 128.16605158
  56.47685355 100.84511914 132.07098715 139.42655864  79.15477515
 104.32290197  51.4051223   66.423534    87.72298161 130.60968638

Conclusion

p-value < 0.05

Reject the Null Hypothesis.